top_features: [
#    categorical features
    'Gender',
    'HairColor',
    'EyeColor',
    'Race',
#    int features
    'Strength',
    'Speed',
    'Durability',
    'Power',
    'Combat',
    'Intelligence',
    'Height',
    'Weight',
#    Boolean features
    'Super Strength',
    'Stamina',
    'Stealth',
    'Enhanced Senses',
    'Flight',
    'Energy Blasts',
    'Energy Absorption',
    'Shapeshifting',
    'Accelerated Healing',
    'Force Fields',
    'Psionic Powers',
    'Weapon-based Powers',
    'Energy Manipulation',
    'Reflexes',
    'Molecular Manipulation',
    'Super Durability',
    'Agility',
    'Longevity',
    'Super Speed']